language: php

sudo: required

addons:
  firefox: "47.0.1"
  postgresql: "9.4"
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
- 5.6
- 7.1
- 7.2

env:
- MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
- MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
- MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
- MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
- MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
- MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
- MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
- MOODLE_BRANCH=MOODLE_33_STABLE DB=mysqli IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js

matrix:
  exclude:
  - php: 7.1
    env: MOODLE_BRANCH=MOODLE_33_STABLE DB=mysqli IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
  - php: 7.1
    env: MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
  - php: 7.2
    env: MOODLE_BRANCH=MOODLE_33_STABLE DB=mysqli IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
  - php: 7.2
    env: MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
  - php: 7.2
    env: MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
  - php: 7.2
    env: MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
  - php: 7.2
    env: MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
  - php: 7.2
    env: MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
  - php: 7.1
    env: MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js
  - php: 7.1
    env: MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql IGNORE_PATHS=amd/src/list.js,provider/powerbi/yui,Gruntfile.js

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install node
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install
  - moodle-plugin-ci add-config '$CFG->curlsecurityallowedport = "";'
  - moodle-plugin-ci add-config '$CFG->curlsecurityblockedhosts = "";'

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
  - moodle-plugin-ci phpunit --coverage-text
